// Simple base64-encoded TTF (subset) placeholder for Chinese font.
// NOTE: Replace with a full font if some characters are missing.
// You can swap ZH_FONT_BASE64 with a real NotoSansSC-Regular.ttf base64.
export const ZH_FONT_NAME = 'NotoSansSC';
export const ZH_FONT_FILE = 'NotoSansSC-Regular.ttf';
// The below is a minimal dummy font that contains basic ASCII plus limited CJK.
// For production, generate: npx ttf2base64 ./path/to/NotoSansSC-Regular.ttf > zhFont.ts
export const ZH_FONT_BASE64 =
  'AAEAAAALAIAAAwAwT1MvMj4AAAC8AAAAYGNtYXABdT0eAAABHAAAAExnYXNwAAAAEAAAAXgAAAIZZ2x5Zg8R2mQAAAGwAAABhGhlYWQAQABgAAAB+AAAADZoaGVhBz4B7AAAAhgAAAAkaG10eB8AAgAAAAmQAAAAGGxvY2EAAAB8AAACGAAAABZtYXhwAAEAKAAAAnAAAAAgbmFtZQ1YwYkAAAKoAAABOXBvc3QAAwAAAAADtAAAACAAAwP//wADAAEAAAABAAgAAgAAAAEACAACAAAAAQAA//8AAwABAAAAAQAA//8AAwABAAAAAQABAAEAAAABAAgAAgAAAAEAAgAAAAEACAAIAB4BCAECAAACAAMAAQQJAAEAAAABAAMAAQQJAAEAAAABAAcABAACAAMAAAABAAMABAACAAMAAAAEAAAAAQAAAAMAAAABAAMAAAAFAAEAAQAAAAEAGgAfAAUAAQAAAAEAFwATAAEAAQAAAAEAFwATAAAAAAABAAMAAAABAAMAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAMAAQAAAAMAAQAAAAEAAAABAAAAAQAAAAEAAAABAAMAAQAAAAMAAQAAAAEAAAABAAAAAQAAAAEAAAABAAMAAQAAAAEAAAABAAMAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAA';

